segmenter_ros:
  ros__parameters:
    params:
      image_params:
        image_size: 640
      ros_topics:
        # Subscriber
        raw_image_topic: "/vs_graphs/keyframe_image"
        # Publisher
        segmented_image_topic: "/camera/color/image_segment"
        segmented_image_vis: "/camera/color/image_segment_vis"
      model_params:
        model_name: "YOLO26"
        model_path: "include/yolo26n-sem-ADE20K.pt"
        conf: 0.5
        overlap: 0.98
      output:
        classes:
          door: [14, 58]
          ground: [3, 6, 11]
          wall: [0, 1, 19]
          window: [8]
    visualize: true
