params:
  image_params:
    image_size: 640
  ros_topics:
    raw_image_topic: "/orb_slam3/keyframe_image"
    segmented_image_topic: "/camera/color/image_segment"
    segmented_image_vis: "/camera/color/image_segment_vis"
  model_params:
    model_name: "maskDino"
    model_path: "include/maskdino_r50_50ep_300q_hid2048_3sd1_panoptic_pq53.0.pth"
    model_config: "src/maskdino/config/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml"
    conf: 0.5
  output:
    classes: [43, 52] # 43: Floor, 52: Wall
