segmenter_ros:
  ros__parameters:
    params:
      image_params:
        image_size: 640
      ros_topics:
        # Subscriber
        raw_image_topic: "/camera/realsense/color/image_raw"
        # Publisher
        instance_mask_topic: "/camera/color/image_instance_masks"
      model_params:
        model_name: "YOLO26"
        model_path: "include/yolo26n-seg.pt"
        conf: 0.5
      output:
        classes:
          movable: [0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
        # [COCO movable classes] person, bicycle, car, motorcycle, airplane, bus,
        # train, truck, boat, and animals: bird, cat, dog, horse, sheep, cow,
        # elephant, bear, zebra, giraffe.
