segmenter_ros:
  ros__parameters:
    params:
      image_params:
        image_size: 640
      ros_topics:
        # Subscriber
        raw_image_topic: "/vs_graphs/keyframe_image"
        # Publisher
        segmented_image_topic: "/camera/color/image_segment"
        segmented_image_vis: "/camera/color/image_segment_vis"
      model_params:
        model_name: "YOLO26"
        model_path: "include/yolo26n-sem.pt"
        conf: 0.5
        overlap: 0.98
      output:
        classes:
          ground: [0, 1, 9]
          wall: [2, 3]
          door: [86]
        # 💡 [Coco Classes] wall: {109, 110, 111, 112, 131}, ground: {87, 122},
        #                   ceiling: {118}, door: {86}, window: {114, 115}
    visualize: true
