params:
  image_params:
    image_size: 640
  ros_topics:
    raw_image_topic: "/orb_slam3/keyframe_image"
    segmented_image_topic: "/camera/color/image_segment"
    segmented_image_vis: "/camera/color/image_segment_vis"
  model_params:
    model_name: "maskDino"
    model_path: "include/panoptic_fcn_r50_512_3x.pth"
    model_config: "src/panopticfcn/config/PanopticFCN-R50-512-3x-FAST.yaml"
    conf: 0.4
  output:
    classes: [43, 52] # 43: Floor, 52: Wall
